### ISSUE TITLE
Accurate Terrain Colliders

### ISSUE THREAD

**Issue by drewmassey-bah** [microsoft/MapsSDK-Unity#10]
Some of the tools that we use require accurate collider components attached to the 3D scenes (i.e. mesh colliders).

The ability to have accurate colliders on the terrain and buildings would allow the tools that we've developed to be able to interact correctly with the terrain.  It would also allow for us to do first person walkthroughs on the terrain.

**Comment by kircher1** [comment]
Version 0.2.0 adds a Raycast API to the MapRenderer. It _may_ help solve some of these scenarios. You could use this to shoot a ray down into the map and detect the distance to the map surface.

While it's unlikely we will be able to add colliders to the current MapRenderer due to how dynamic the geometry is, we can revisit this for [immersive mode](https://github.com/microsoft/MapsSDK-Unity/issues/2). Here, the map is no longer clipped, so providing a mesh collider could be feasible.

**Comment by drewmassey-bah** [comment]
For the Raycast API, is that something that can be configured on the Map Renderer component itself, or is it something that allows a new script to use Raycasting to interact with the map?

Real time collider generation is a pretty difficult problem.  I think to what you are talking about with immersive mode you can generate the mesh and feed it into a Mesh Collider component.  A possible solution could be to clip the displayed map from the map renderer and then feed the mesh geometry into the Mesh Collider component.

**Comment by kircher1** [comment]
The raycast API is something you'd have to call on the instance of MapRenderer via a script, e.g. mapRenderer.RayCast(ray, out result).

In the current rendering mode of the map, the underlying meshes that are being rendered could be clipped differently from frame-to-frame, e.g. when the map center is moving (animating/panning/zooming) the region of the map being clipped is constantly changing. To accurately represent the map with a mesh collider then, it would require regenerating the mesh collider anytime the map terrain changes, i.e. every frame. This would be a prohibitively large perf hit for common scenarios.

For immersive mode, there's no clipping going on, so we could use MeshColliders directly for each tile of the map. That should be more straightforward since you just need to generate the mesh collider *once* for each tile.

**Comment by MephestoKhaan** [comment]
Any updates on this? Is inmmersive mode already supported? I can't find any reference to it in the examples from the latest build. (Thanks, this is impressive work)

**Comment by kircher1** [comment]
Immersive mode is not supported. We'll make some noise once we have it available.

**Comment by MephestoKhaan** [comment]
Do you have a rough eta? How can I help? I would love to move certain app I am developing with a different map provider to this one...

**Comment by samdemmyhardy2** [comment]
Hi, Noob here... am I right in thinking that if this request was supported - it would allow objects to collide with buildings etc? Thanks
