### ISSUE TITLE
Local Map Height & Elevation incomprehension

### ISSUE THREAD

**Issue by TLesaunier-artefacto** [microsoft/MapsSDK-Unity#100]
Hi guys, 

First, thanks for this amazing SDK. I'm using it to see 3D models projet in a real context, and it's wonderfull, thanks a lot.

But I have some questions for you. (using Unity.4.12f1).
My goal with your SDK is to put 3D model in there real futur environnent, like a new buildings in 3D before it be build in the place I'm looking.
When we put the Map Renderer "Map terrain type " to "Default", we have an elevation. This elevation is the result of comparing our position with the sealevel I think ( right ? ). So, If I want to put a 3D model on my MapRenderer Center, I have to manage an offset to compensate for the sealevel. But this offset is different each time my center move, and I don't find a way to calculate it. When I'm using the "Flat Terrain Type", I'm ok but I have not 3D buildings :-/.  
So, I'm looking for a way to moveing down the MapRenderer object in Unity to manage the offset due to sealevel.

An idea guys ? 

Thanks for your time,

Thibault

**Comment by kircher1** [comment]
The `MapPin` component can be used for this. Check out the [Attaching GameObjects](https://github.com/microsoft/MapsSDK-Unity/wiki/Attaching-GameObjects-to-the-map) wiki page.

**Comment by kircher1** [comment]
Also, in this case, you will likely want to use the "Real World Scale" option on the MapPin. When enabled, as the map is zoomed in or out, the MapPin object will maintain a realistic scale rather than a constant scale. This is what you would want for something like a building.

Using the real world scale option though means the building model or it's GameObject's Tranfsorm will need to scaled to it's real-world size in meters.

To make this a little more clear, here is how the GameObjects in a scene heirarchy can be setup:

- MapGameObject (has MapRenderer component)
   - BuidlingsMapPinGameObject (has MapPin component, uses Real World Scale)
      - BuildingGameObject (the Transform should be scaled so that the model is the real world size of the building in meters)

**Comment by TLesaunier-artefacto** [comment]
Thanks for this idea. I will try it.

One bug for me , if I do it like this, Pin Componenet is always disable when Unity Scene is playing : 

MapGameObject (has MapRenderer component)
   * BuidlingsMapPinGameObject (has MapPin component, uses Real World Scale)
          *BuildingGameObject

**Comment by kircher1** [comment]
I'm not able to repro the bug, but it shouldn't be required to force enable the MapPin.

Make sure the MapPin _component_ is enabled in the editor. If it is disabled, the GameObject will be deactivated. The MapPin GameObject will also be deactivated when the MapPin's latitude/longitude is not in the bounds of the current map's view. If the MapPin component is enabled and the latitude/longitude is in view, then the GameObject should be enabled (in editor or playmode).
