### ISSUE TITLE
Map not showing up in Camera's ReadPixels()

### ISSUE THREAD

**Issue by LefanTan** [microsoft/MapsSDK-Unity#101]
Hi, I've created a screen shot scripted that takes a photo of the map from a second camera. 

While the screen shot does work, the map renderer objects are not showing in the pixels taken of the camera using ReadPixels, as below.
![missing](https://user-images.githubusercontent.com/12474777/98407080-a5624080-2034-11eb-8e6c-aff721b3f428.gif)

I suspect that the map is not rendered conventionally, if so, how do I still capture an image of the map?

**Comment by kircher1** [comment]
Graphics.DrawMesh is used to render the map content, but I believe it only renders to cameras that are _enabled_. If you are following the [`Camera.Render()`](https://docs.unity3d.com/ScriptReference/Camera.Render.html) docs from Unity, that code sample expets the camera to be disabled in order to explicitly control when it's rendered. If that's the approach you're using, maybe rather than calling Render() manually on the Camera, enable it for one frame instead? Then on the subsequent frame, copy the camera's RenderTarget pixels to a different texture.

**Comment by LefanTan** [comment]
Thank you for the idea! I called WaitForEndOfFrame() in an async function and it works now.
