### ISSUE TITLE
Exist a way of improve the raycast performance?

### ISSUE THREAD

**Issue by Acuolo** [microsoft/MapsSDK-Unity#103]
Im trying reacreate a collision with raycast, but method of the API has a low performance for this.

Exist a change of use RaycastCommand with your SDK?
https://docs.unity3d.com/ScriptReference/RaycastCommand.html

Thanks!

**Comment by kircher1** [comment]
Because the content of MapRenderer doesn't use Unity colliders/mesh colliders, the RaycastCommand won't return results related to the MapRenderer. This is why MapRenderer provides a separate Raycast API.

I think there are some improvements that could be made to the MapRenderer raycast implementation which could speed it up though. Similarly, there may be a way to make the API work async so it can be called off of the main thread and/or in parallel with other raycasts.

There's no quick fixes here though unfortunately. Will leave this issue open to track.
