### ISSUE TITLE
MapRenderer.SetMapScene(...) seems to have stopped smooth stepping the beginning and the end of the animation

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#105]
**Describe the bug**
MapRenderer.SetMapScene(...) used to smooth step the beginning and the end of the animation. I'm particularly familiar with MapSceneAnimationKind.Linear from version 0.7. In 0.10 the animation ends abruptly without smoothing.

**To Reproduce**
Call below method from a script. Use Linear animation kind

`public WaitForMapSceneAnimation SetMapScene(
            MapScene mapScene,
            MapSceneAnimationKind mapSceneAnimationKind = MapSceneAnimationKind.Bow,
            float animationTimeScale = 1.0f)`

**Expected behavior**
Should smooth step the animation

**Environment (please complete the following information):**
 - Unity version: 2019.4.13f1
 - Maps SDK Package version: 0.10.0

**Comment by kircher1** [comment]
This was removed in 0.10.0 so that linear zooming worked better in a double-tap to zoom interaction. The smoothing there was out of place, although for other scenarios, it does seem useful still. For a future release, the smoothing could be added back under a `MapSceneAnimationKind.SmoothedLinear` or something like that.

In the meantime, the default [`MapSceneAnimationController`](https://github.com/microsoft/MapsSDK-Unity/blob/428b5dba9d5e1d6ec99c15cc58edf2eeda56d100/SupportingScripts/Runtime/Scripts/MapRenderer/MapScene/MapSceneAnimationController.cs) could be copied to a local script, renamed, and then modified to add back the smoothing (~line 102):
```C#
    if (_isLinearAnimation)
    {	           
        // Ease t to slow down the start and stop of animations.	
        t = (float)SmoothStep(0.0f, 1.0f, t);	
        LinearAnimation(t, out zoomLevel, out location);
    }
```

Then MapSceneAnimations using the custom controller can be started like this:

```C#
    map.SetMapScene(
        mapScene,
        new CustomMapSceneAnimationController(),
        mapSceneAnimationKind);
```

**Comment by kircher1** [comment]
There's a new enum type for `MapSceneAnimationKind.SmoothLinear` in 0.10.2.
