### ISSUE TITLE
Status about Android support

### ISSUE THREAD

**Issue by JustinFincher** [microsoft/MapsSDK-Unity#11]
Hi, I know that this SDK is provided mainly for Windows Mixed Reality usage, but I think it would be cool if this could be running on mobile devices. I saw the [0.2.0 changelog](https://github.com/Microsoft/MapsSDK-Unity/blob/master/CHANGELOG.md#020---2019-05-24) and there it mentions 'Fallback to terrain-only rendering' for Android, but the 0.1.5 runs fine on my Pixel 3 with meshes correctly displayed. As the library is provided as binary I cannot modify the source, but to hope Android support can be officially added back even if only a subset of Android devices would support this SDK, thanks!

**Comment by kircher1** [comment]
Just to clarify, this fallback only happens if the device doesn't support for BC1 textures. If Pixel 3 was rendering the high-resolution meshes in 0.1.5, it should continue to work in 0.2.0. Let me now if that's not the case though!

Prior to this change, devices that didn't support BC1 textures would still "render" the high-resolution meshes, but the texture would appear entirely black. Now, if BC1 textures are not supported, then the map falls back to the elevation-only rendering which uses a basic RGB texture format, which is widely supported and will render correctly.

The variable here is whether the hardware (GPU) supports the BC1 texture format. For Windows 10, it is guaranteed. For OpenGL ES, it is not guaranteed, but I've seen many Android devices with GPUs like the Adreno including support anyways (Pixel 3 has an Adreno 630 GPU). For iOS, I'm not sure whether the GPUs used in those phones include support for this texture format.

**Comment by JustinFincher** [comment]
Hi, I think my Pixel 3 can handle high-res meshes although Unity did complain about the BC1 texture format (in 0.1.5):
```
2019/05/28 18:30:42.533 14634 14650 Warn Unity: 'DXT1' is not supported on this platform. Decompressing texture. Use 'SystemInfo.SupportsTextureFormat' C# API to check format support.
```

It seems that Unity thinks the Pixel 3 cannot do hardware compression so it runs a software compression on the texture (if forced to do so, I think that's what the case in 0.1.5). The good thing is meshes are displayed correctly despite the BC1 texture format is reported as unsupported in Unity. I have some screenshots posted below for a reference.

| ![image](https://user-images.githubusercontent.com/8359912/58471082-a9b6d880-8175-11e9-90ff-2d17e58ac76e.png) | ![image](https://user-images.githubusercontent.com/8359912/58471049-91df5480-8175-11e9-8b65-bd01461bc44a.png) | ![image](https://user-images.githubusercontent.com/8359912/58471413-6315ae00-8176-11e9-92cc-bcc2290143ad.png) |
|----------------|-----------------|-------|
| 0.1.5 (Editor) | 0.1.5 (Android) | 0.2.0 (Android) |

Environment:
- Unity 2019.1.4f1
- Pixel 3
- Test Coordinate (40.712903,-74.013203,zoom level 18)

**Comment by kircher1** [comment]
Ahh, so Unity is automatically decompressing to RGB. Good to know. I will rollback this new fallback logic in the next version since it is already handled by Unity. Thanks for raising this!

**Comment by JustinFincher** [comment]
Great! Thanks for your effort on this!

**Comment by kircher1** [comment]
0.2.1 has been published. Please reopen if this doesn't bring back the high-res meshes. Thanks!
