### ISSUE TITLE
ReflectionTypeLoadException - Map Renderer

### ISSUE THREAD

**Issue by userint** [microsoft/MapsSDK-Unity#113]
**Describe the bug**
Loading Maps SDK into new project. Map Renderer script dropdown does not display correctly and throws ReflectionTypeLoadException error. 

**To Reproduce**
1. Install Unity 2019.4.15f
2. Setup new UWP project (targeting Hololens 2)
3. Modify manifest.json
4. Create new game object and attach map renderer component
5. Click map renderer drop down in inspector.

**Expected behavior**
Maps SDK works.

**Screenshots**
![img](https://user-images.githubusercontent.com/81594847/112908401-cdad2180-9132-11eb-899a-7f73c244f987.JPG)
![img](https://user-images.githubusercontent.com/81594847/112908616-2aa8d780-9133-11eb-98c7-eef0d4c9adff.JPG)

**Environment (please complete the following information):**
 - Unity version: 2019.4.15f1
 - Maps SDK Package version: **Tried** from 0.8.1 to 0.10.1

**Additional context**

**Comment by kircher1** [comment]
I haven't been able to repro this so I wonder if the exception is due to another assembly in your project that is somehow causing the GetTypes reflection API to fail?

In any case, I think this error could be handled gracefully by our custom component rendering code so that it doesn't make the UI unusable.

As a work-around, you can try right-click on the Inspector tab and try switching it to the Debug view: 

![image](https://user-images.githubusercontent.com/20366429/113454239-9fdb0d80-93bc-11eb-805c-774191889b89.png)

**Comment by kircher1** [comment]
Fixed in 0.10.2.
