### ISSUE TITLE
What is the right procedure to use custom elevation data?

### ISSUE THREAD

**Issue by simoamico94** [microsoft/MapsSDK-Unity#120]
Hi, I'm struggling to use custom elevation data with the MapsSDK. I've imported and used custom texture tiles, but with elevations seems very confused and not well explained. I have zero background knowledges related to maps formats and structure, I've tried to learn something on the internet but still I'm not able to use my custom elevation data. I've downloaded a very big (5GB) .tif file from the EU-DEM v1.1 database of copernicus.eu, but I don't know what to do with it. I've also started the trial of ArcGIS pro to try to split it into several tiles but I don't know which parameters to put in the export raster tab (not sure if it's the right tool to split it). 
I've also downloaded the sample unity project and looked at the CustomElevationExample scene but I still can't undestand where did you get these .et files, how are they working and especially how I can create them from a more common file format (like the one I've downloaded). 

Can someone help me?

Thank you!

**Comment by kircher1** [comment]
Using custom elevation sources is a more advanced task if you are having to generate the tiles from raw source data. I can only offer high level advice rather than specific guidance as it largely depends on the format of the source data and what tools you use to work with the data.

The first thing you'll need to do is ensure the source tif is transformed to Web Mercator (EPSG:3857). Similarly, elevation data needs to be transformed relative to the WGS84 ellipsoid. Then you'll need to generate "tiles" from the projected tif using the common Web Mercator quad-tree scheme explained [here](https://github.com/microsoft/MapsSDK-Unity/wiki/Customizing-data-sources). ArcGIS may be useful for this, but specific questions on how to achieve these things are better posed to their forums.

Note, as part of generating this tile set, you'll need to decide how the data is encoded. I suggest finding a format that is fast to decode in Unity, and if size is a concern, something that is compressed.

Once you have a set of tiles, you can implement a custom [ElevationTileLayer](https://github.com/microsoft/MapsSDK-Unity/wiki/ElevationTileLayer), which handles the transforming the tile data to an [ElevationTile](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#elevationtile) that the map understands. Note there are various ways to construct an ElevationTile, but ultimately you are specifying the height values, either directly or normalized in some way.... Also, to be clear on this point, the ElevationTile represents a single Web Mercator tile, so the ElevationTileLayer would handle converting one of your custom tiles to an ElevationTile, assuming the tiles in your tile set are in fact Web Mercator-based as described above.

Note, how you decode the tile it depends on how the tile was encoded. The tiles used in the sample project are leveraging a custom format that was easy to work with and efficient to decode, although not great from a size perspective (they are not compressed). The layout of these tiles are described in the code comment [here](https://github.com/microsoft/MapsSDK-Unity/blob/3686a9d6cb647799b7f926fae110e060a88f0cab/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CustomElevationExample/Scripts/CustomElevationTileLayer.cs#L48).

**Comment by simoamico94** [comment]
Thank you for your answer! Actually the raw source data is the only one I've found. If you know a tool from which I can download elevation tiles in the correct format, ready to use, it would be awesome.

**Comment by kircher1** [comment]
To clarify, the idea with the ElevationTileLayer is that you would provide/implement the decoding logic for the elevation data. Unfortunately, there isn't a super common representation for elevation data. Some folks use grayscale images, some use GeoTIFF, and there are various other schemes/compressions that could be applied. The one used in the sample project is entirely custom, and intended to be fast and relatively simple to decode. 

You could encode elevation data using the same convention from the sample and reuse that decoding logic as well, but you'd still need to re-project and tile up the source data first, and that is the more involved part of this process. 

Also, the resolution of the data provided by the default ElevationTileLayer is going to be equivalent or better than the resolution of the data from EU-DEM. So at least from a quality perspective, the default online source used by the SDK should be sufficient.
