### ISSUE TITLE
Support Universal Render Pipeline

### ISSUE THREAD

**Issue by adsilcott** [microsoft/MapsSDK-Unity#15]
Are there any plans to support the new Scriptable Render Pipeline?

**Comment by kircher1** [comment]
This is a future item for us to address. No immediate plans to provide default LWRP/HDRP variants of the shader.

I assume the shaders we provide do not work with LWRP/HDRP (I haven't tried though to confirm). We do allow for specifying a custom material to render the map, so if projects are targeting these pipelines, it is possible to get the map rendering correctly under an SRP by converting the existing shader and creating a new material based on that.

**Comment by kircher1** [comment]
Converting to a feature request.

**Comment by muhammedyusuf-sermet** [comment]
@kircher1 yes, with LWRP, the map object just renders as pink. Default support for LWRP would be tremendous.

**Comment by visose** [comment]
I'd like to use this on project using the High Definition Render Pipeline (HDRP). I understand there's no support for this yet.
I was thinking of attempting to port the shaders, as this is the main issue. But there's also a lot of display related code under the compiled Microsoft.Maps.Unity.dll, specially on the MapRendererBase class.
I'd like to ask if you can confirm I wouldn't have to change anything inside the .dll to be able to port this.
This could be, for example, code that creates a material using an old shader, Shader.Find("Standard"), or sets material properties assuming old shaders.

**Comment by kircher1** [comment]
The code related to the shaders in MapRenderer base is doing a couple of things.

1) It makes a copy of the custom terrain material you specified in the MapRenderer component's settings and creates a couple of variants for it corresponding to combinations of various defines (different types of map data are rendered with differently, e.g. elevations vs 3d models, but they use the same shader). So, the custom material being set on the MapRenderer is sort of like a master copy. Use the existing terrain shader as a reference in that respect.

2) Each frame, per chunk of the map that needs to be rendered for the current extents, it sets a material property block on the variant of the material and then performs a draw call. 

So overall, I think should be possible to set a custom terrain material on the MapRenderer that uses an SRP based shader too. 

One potential area that may not be possible to convert is the rendering of the side-walls of the map because that effect uses a shader that isn't overridable. That effect also requires first rendering to a separate camera/render target and sampling from that later. I'm not sure how that would work in HDRP land. Either way, the side wall could be disabled in the MapRenderer settings aren't needed for your scenario.

**Comment by QGNGO** [comment]
> I'd like to use this on a project using the High Definition Render Pipeline (HDRP). I understand there's no support for this yet.
> I was thinking of attempting to port the shaders, as this is the main issue. But there's also a lot of display related code under the compiled Microsoft.Maps.Unity.dll, specially on the MapRendererBase class.
> I'd like to ask if you can confirm I wouldn't have to change anything inside the .dll to be able to port this.
> This could be, for example, code that creates a material using an old shader, Shader.Find("Standard"), or sets material properties assuming old shaders.

@visose, did you were able to make HDRP shaders ? Because i'm really interested in using them on my HDRP student project.

@kircher1, @visose, I would like to port those shaders but i actually don't know how to download the standards ones neither how to replace them ... How should I start ?

**Comment by kircher1** [comment]
Check here for how some pointers: https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#custom-materials-and-shaders

**Comment by visose** [comment]
@QGNGO sorry, we didn't make an attempt to port this for the time being, decided is too high risk. We don't really know yet how to properly write custom HDRP shaders, it's more complex than the built in pipeline, so we can't even guess how long it could take us to port.

**Comment by fra3point** [comment]
Hello,

I have a very basic solution for this (Unlit, no MRTK support). I basically converted the MapsSDK/StandardTerrainShader in a simpler Vertex/Fragment shader. I also duplicated some .cginc files so that I could place them in the same folder of the modified shader. It works fine with Universal Render Pipeline (probably in HDRP, too, but not tested).

![immagine](https://user-images.githubusercontent.com/34285897/115988600-ca367a00-a5ba-11eb-9251-ac894c2d057e.png)

You can try this .unitypackage

[MapsTerrainURP.zip](https://github.com/microsoft/MapsSDK-Unity/files/6371673/MapsTerrainURP.zip)

**Comment by HoloMoto** [comment]
@fra3point 
Thanks to your Unitypackage, the problem that was plaguing me has been solved.

　I was trying to combine ShadeGraph and VFXGpraph with MapSDK to create an educational application.
　Your package worked perfectly in my URP environment.
　Thank you.

**Comment by kircher1** [comment]
Thanks for sharing @fra3point! 

Unity's docs on [writing custom URP shaders](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.2/manual/writing-shaders-urp-basic-unlit-structure.html) say that custom URP shaders must be written in HLSL. The shaders you've shared are using CG though, so I'm curious how it works. Do you know why using HLSL isn't necessary here?

**Comment by fra3point** [comment]
> 
> 
> Thanks for sharing @fra3point!
> 
> Unity's docs on [writing custom URP shaders](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@8.2/manual/writing-shaders-urp-basic-unlit-structure.html) say that custom URP shaders must be written in HLSL. The shaders you've shared are using CG though, so I'm curious how it works. Do you know why using HLSL isn't necessary here?

Hello,

as mentioned [here ](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.2/manual/writing-shaders-urp-basic-unlit-structure.html), URP supports CG. HLSL is preferable because it supports [SRP Batching](https://docs.unity3d.com/Manual/SRPBatcher.html), which is very good for optimization because batches are created by shader variant and not by material.

So it is still possible to write classic vertex/fragment shaders in URP!

**Comment by kircher1** [comment]
Thanks for the info. My initial thoughts are that URP variants of the maps shaders should ultimately be written with HLSL to unlock that SRP batcher integration. (It seems like a good optimization Unity has made to their render workload.)

However, since these HLSL shaders seems to require URP specific includes, these shaders would need to be separated out to some sort of MapsSDK-URP package so that projects using that are still using the built-in pipeline won't run into errors about missing includes. 

That being said, CG shaders are a great stopgap for folks needing URP support now!! So again, thanks for sharing.

**Comment by fra3point** [comment]
I'm pretty sure that you won't benefit much from SRP Batching because the map renderer produces just a few draw calls. I made some tests with different Detail Offset values, and with my shader the draw calls are:

- Low: 5
- Default: 13
- High: 31

On modern GPUs 31 draw calls are not much, so I wouldn't care a lot about that. 

But there is one more things you may want to consider and that would probably make HLSL a good choice: URP doesn't support MultiPass shaders (even if written in CG), so you won't be able to write lighting or Shadow Caster passes in frag/vert shaders.

**Comment by fra3point** [comment]
> 
> 
> @fra3point thank you for the unitypackage, however I am unable to add it to my project: it says there is nothing to import - all assets are already in your project. Please advise on how I can enable URP rendering of the Bing Maps SDK.

Sounds strange... I've just tried importing the package in multiple projects with different Unity versions (2020.2, 2019.4) and worked all the times. What Unity version are you using?

**Comment by kircher1** [comment]
As part of the 0.11.0 update, the existing standard shaders in the SDK have been converted to HLSL URP compatible versions and added to the repo as part of a "URP support package". This package can be installed to Unity projects via the Git URL.

[Check this wiki page for install instructions.](https://github.com/microsoft/MapsSDK-Unity/wiki/Universal-Render-Pipeline-support)

These new URP shaders support shadows as well as the various map-specific stuff, like the clipping edge wall.

And note, the 0.11.0 version is required as other updates to the core SDK were necessary to support URP.

---


![image](https://user-images.githubusercontent.com/20366429/120576294-654f1a80-c3d7-11eb-8720-36ba252d4665.png)

With that, I'm closing this issue out. And thanks again @fra3point for sharing an intermediate solution!
