### ISSUE TITLE
Method to get altitude given a LatLon value?

### ISSUE THREAD

**Issue by sebascal1** [microsoft/MapsSDK-Unity#152]
Hi, I was wondering if there was an implemented method within the Bings Maps SDK to get the elevation at a given latitute and longitude coordinate without having to use a raycast or call the Bings Maps Rest Services? Thanks in advance.

**Comment by kircher1** [comment]
No, this isn't possible. If you are trying to query the elevation of a point on the map, the raycast is the best path. If you are trying to pin an object to the map at the surface (or some offset from the surface) try out the MapPin system. This will automatically keep a GameObject positioned relative to the map surface... Otherwise, the elevation REST service would be the way to go for querying arbitrary elevations.
