### ISSUE TITLE
Custom Local Map Dimension

### ISSUE THREAD

**Issue by fakeart** [microsoft/MapsSDK-Unity#153]
Initially the range is from 0.1 to 3. Adding multiple maps to one scene and fitting seamlessly is not the best solution. Is it possible to increase local map dimension?

![image](https://user-images.githubusercontent.com/23584686/146552915-71e61ca4-1376-4a41-bbb3-ae3f730a48c5.png)

**Comment by kircher1** [comment]
This constraint is in place to ensure performance can be maintained while rendering the map. More detailed answer in similar question: #77. Adding multiple maps is one possibility to expand the area but it will suffer from same performance degradation, if not more so, since some of the data being requested by these neighboring maps is likely going to be redundant.
