### ISSUE TITLE
Converting from Unity space to Map space

### ISSUE THREAD

**Issue by cobrauf** [microsoft/MapsSDK-Unity#16]
Hi, is there a way to convert from Unity's transform.position to a lat/lon/alt so I can pin an object to the map? I looked through the API docs and couldn't find a way to do so.

I work at AfterNow, our found Philippe Lewicki said he may have spoken to you at MR Dev Days in Seattle. It'd be great to have your contact info for follow up questions, thank you!

**Comment by kircher1** [comment]
This conversion logic will be provided as a supporting script in the next version of the NuGet package, 0.2.2, coming soon! It required a small API addition to the MapRenderer in order to work, which is why I can't share a preview unfortunately, i.e. the script wouldn't compile against the current version.

We are still working on creating a separate channel that can be used for more direct/private communication. I will reply back with the contact info when it's ready.

**Comment by cobrauf** [comment]
Sounds great! any estimate on the release date?

**Comment by kircher1** [comment]
The package is now available! It includes [this script](https://github.com/microsoft/MapsSDK-Unity/blob/master/SupportingScripts/Scripts/MapRendererTransformExtensions.cs), which extends the MapRenderer to provide these coordinate space conversion methods.

**Comment by cobrauf** [comment]
Perfect, thanks!
