### ISSUE TITLE
Is there any way to display specific area but mask around that area

### ISSUE THREAD

**Issue by ferdi12-tr** [microsoft/MapsSDK-Unity#198]
Hi there, I'm dwelled on some problem and need some help or useful perspective to solve this problem.
Now I want to display only an area of map but the other areas must not be displayed and I want to mask that area somehow.
So, the problem is display an  GeoBoundingBox area and mask or just ignore another area, and when zoomed in or out, this masked area or ignored area must be masked or ignored accordingly.

let make this problem more clear, say I want to display Turkey's map but the neighbouring country of Turkey's also displayed and zoomed accordingly and I want to masked or ignored all neighbouring country of Turkey and displayed only Turkey map.

Maybe there isn't a direct solution but a fresh perspective can be useful.

Thanks!

[This is the solution](https://samples.azuremaps.com/polygons/polygon-mask-with-dynamic-styling) but when it comes to unity I don't know how to make my map like this

**Comment by kircher1** [comment]
Yeah, the masking is not something supported by this SDK... But since one can customize the shader being used to render the map, a lot is possible with some work. A potential way to approach this would be to create and provide a custom texture layer that provides the mask data and then use the custom shader to grey-out pixels outside the area of interest.
