### ISSUE TITLE
Radial map generation

### ISSUE THREAD

**Issue by shyam-tilt** [microsoft/MapsSDK-Unity#25]
Is there a way to generate the map radially?

**Comment by kircher1** [comment]
Not currently, but this feature is on the road map! We hope to have it available in the 0.5 version of the SDK. 

The closest way to achieve a circular map now would require disabling the map walls and [modifying the terrain material's shader](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#custom-materials-and-shaders) to discard pixels based on a circular radius rather than a rectangle.

**Comment by jiangshen** [comment]
We have released version 0.5 which adds radial map generation support. You can now select under `Inspector `> `Map Layout` > **`Map Shape`**. The options are **Block** or **Cylinder**

More details can be found [here](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#map-layout).

**Comment by TerraSame** [comment]
Awesome!
