### ISSUE TITLE
Huge maps?

### ISSUE THREAD

**Issue by jackcrane** [microsoft/MapsSDK-Unity#28]
Is there some way to make a huge map for whole city-scale renders? It seems as though this is limited to 3x3 for the local map dimensions. If i change the zoom level, the texture quality is substantially decreased.

**Comment by kircher1** [comment]
This is related to #2. Currently the map is restricted in size due to performance overhead of rendering a larger area. We are looking at improvements to the core parts of the SDK that would allow for removing this sort of restriction.

The highest quality map now can be achieved by using the max layout size (3x3) and increasing quality slider to highest setting. Note however, performance may be an issue in this configuration.

Also note, zoom level 20 is displaying the highest detail data available.

**Comment by yosun** [comment]
I don't notice any performance limits at 3x3... Why not have the layout size limit be a bit larger? 3x3 feels a bit arbitrary... 

https://github.com/microsoft/MapsSDK-Unity/issues/77
