### ISSUE TITLE
Loading Callbacks

### ISSUE THREAD

**Issue by Barokoli** [microsoft/MapsSDK-Unity#31]
Hi,
first of all: Thanks for this amazing API!

Is it possible to get Information about the loading status of the map? Is there maybe a callback or onload that i can use to trigger events when a location has been loaded?

Edit: As a workaround I am currently testing with raycasts wether the terrain has been loaded.

**Comment by kircher1** [comment]
No callbacks for this currently. I didn't consider the raycast method but that is clever workaround!

Regardless, this is a great feature request. Updating the labels accordingly.

**Comment by Ristophonics** [comment]
Can I add a request for a map isChanging callback for cases like   "SetMapScene()" ..  It would be cool to know when the map is still panning or zooming. 

not sure if the same as [Usage of MapRenderer.SetMapScene() inside Editor #71](url)

**Comment by kircher1** [comment]
@Ristophonics, if you mean a way to wait for the animation to complete this is possible: 

_The SetMapScene API returns a yieldable object that can be used within a co-routine to wait until the animation has completed. Note, it is not required to call the animation from a co-routine. If the yield-ing is not required, the object returned from SetMapScene can be ignored._

Code example [here](https://github.com/microsoft/MapsSDK-Unity/blob/master/SampleProject/Assets/Microsoft.Maps.Unity.Examples/CityTourExample/Scripts/SeattleTour.cs):

```csharp
    private IEnumerator RunTour()
    {
        yield return new WaitForSeconds(5.0f);

        while (isActiveAndEnabled) // loop the tour as long as we are running.
        {
            foreach (var scene in MapScenes)
            {
                yield return _map.SetMapScene(scene); // <-------- yield continues when the animation is complete.

                yield return new WaitForSeconds(3.0f);
            }
        }
    }
```

This approach only helps to know when the animation completes, i.e. map's center and zoom level is done changing. It doesn't tell you though when the data at the animated-to location has been resolved. That is what this issue is tracking overall and still something that we will be looking at providing through the MapRenderer API.

**Comment by kircher1** [comment]
For the more general issue, a couple of APIs have been added in **0.9.2** that can be used to detect when the map has completed loading data for a given area.

1) MapRendererBase.IsLoaded (bool property)
2) MapRenderer.WaitForLoad() which is used in a IEnumerator just like MapRenderer.SetMapScene.
