### ISSUE TITLE
Altitude Issues

### ISSUE THREAD

**Issue by adsilcott** [microsoft/MapsSDK-Unity#44]
I've been trying to place markers in a scene with a certain offset from sea level, but the sea level that I get seems to vary a lot depending on the location. I'm using something like:

    var currentPosition = new LatLonAlt(currentLat, currentLon, altitudeOffset);
    transform.position = mapRenderer.TransformLatLonAltToWorld(currentPosition);

I'm finding that the offset needs to be -16 to match the apparent sea level when zoomed out, and anything from -35 to -20 to match the apparent sea level when zoomed in. I wouldn't expect it to be perfect, but is there a way to get a more accurate alignment?
  
I'm using Unity 2018.4.15f1 for this project and version 0.2.2 of the Maps SDK

**Comment by kircher1** [comment]
It's possible this is expected, although feel free to share some lat-lons of specific areas. The reason this may be expected is that the altitude reference system that you are working in here is relative to the WGS84 ellipsoid, which is perfectly flat. While it may be close in some areas, this is not actually the same as "sea level", which undulates relative to this ellipsoid reference.

If you haven't tried already, I suggest using the [MapPin](https://github.com/microsoft/MapsSDK-Unity/wiki/Attaching-GameObjects-to-the-map) component to attach game objects to the map. Importantly, if you want the pins to align with the terrain, you need to use Surface (or Terrain) for the altitude reference. This will cause the GameObject to be positioned relative to the surface of the map, rather than the aforementioned ellipsoid.

![image](https://user-images.githubusercontent.com/20366429/74286006-cf701780-4cdb-11ea-9f43-b0997aab659d.png)

**Comment by adsilcott** [comment]
I suspected that might be the problem. 
Thanks for pointing out the Map Pin component. I think the best I'll be able to do is to manually pin an object where I know the ocean is at each location I'm working with, then measure the height from sea level using that object as a reference.
