### ISSUE TITLE
Cannot install 'Microsoft.Maps.Unity' using NuGetForUnity.

### ISSUE THREAD

**Issue by jonnyhong** [microsoft/MapsSDK-Unity#54]
**Describe the bug**
Cannot install 'Microsoft.Maps.Unity' using NuGetForUnity.

**To Reproduce**
1.Unity 2019.3.13 and NugetForUnity.install unitypackage
2. Switch platform to UWP (Same without switch platform)
3. Search Microsoft.Maps.Unity and click the Install button
4. Check the console tap for errors

**Expected behavior**
[ BadReadException: Could not read block - no data!  (position 0x0009CBF6) ] error occurred

**Screenshots**
![error](https://user-images.githubusercontent.com/65284081/81801818-f5fa5480-954f-11ea-903f-cc269a472fc3.png)

**Environment (please complete the following information):**
 - Unity version:  2019.3.13f1
 - Maps SDK NuGet Package version: NuGetForUnity 2.0.0 / Microsoft.Maps.Unity version 0.7.1

**Additional context**
In addition, I would like to know if I can set the map to 2D(street and road? view).
(Like a typical map.)

**Comment by kircher1** [comment]
I'm not sure why the [NuGet for Unity](https://github.com/GlitchEnzo/NuGetForUnity) plugin is failing to unzip the package.

Instead, you could download the NuGet package itself here: https://www.nuget.org/packages/Microsoft.Maps.Unity/

Since the NuGet package is a zip container, renaming/adding a .zip extension to the package will allow you to extract the contents. 

FWIW, we're looking at providing the SDK as a Unity package which can be managed through the Package Manager UI in the editor, i.e. not NuGet based. 

> In addition, I would like to know if I can set the map to 2D(street and road? view).
> (Like a typical map.)

That should be available in upcoming 0.8 release as a TextureTileLayer.
