### ISSUE TITLE
Add support for MRTK Standard Shader properties to customize the look of the map

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#56]
**Is your feature request related to a problem? Please describe.**
Please add full support for MRTK Standard Shader properties to customize the look of the map. Currently only property that affects the look is the diffuse color.

**Describe the solution you'd like**
Support features such as rim light, environmental lighting, additive blending etc.

**Additional context**
MRTK Standard Shader is a light weight shader, developed as a more performant and feature packed replacement for Unity's Standard Shader.

**Comment by kircher1** [comment]
Thanks for pointing out the other features in MRTK standard shader that would be worth integrating! 

Currently the map's shaders support MRTK's 'hover light'. The corresponding checkbox in the MapRenderer needs to be enabled though in order for this to work, otherwise the code paths in the shader are disabled by an ifdef... Default for this checkbox I believe is disabled. 

![image](https://user-images.githubusercontent.com/20366429/82359424-b3f06900-99bc-11ea-9cdb-649d0e88ddb7.png)

If possible, you could extend the map's shaders in your Unity project to add these MRTK-specific features. The relevant shaders that need to be updated are `StandardTerrainShader-MapsSDK.shader` and `StandardClippingVolumeShader-MapsSDK.shader`.  Note, the map's shaders are committed to GitHub [here](https://github.com/microsoft/MapsSDK-Unity/tree/master/SupportingScripts/Shaders).
