### ISSUE TITLE
How can I get info about ground level altitude in certain LatLon?

### ISSUE THREAD

**Issue by Pysiokot** [microsoft/MapsSDK-Unity#58]
How can I get info about ground level altitude in certain LatLon?
What about LatLon that are outside MapRenderer radius?

**Comment by SiriusA7** [comment]
This would be super useful if possible !

**Comment by HKBSC** [comment]
One way is to create a MapPin at that location (MapPin.Location) and get MapPin.Altitude. You can set MapPin.AltitudeReference to Terrain or Surface based on your use case.

**Comment by SiriusA7** [comment]
> One way is to create a MapPin at that location (MapPin.Location) and get MapPin.Altitude. You can set MapPin.AltitudeReference to Terrain or Surface based on your use case.


Already tried that. Doesn’t work because the altitude field doesn’t get updated, only the MapPins transform gets updated. Best that can be done with this approach is feeding the position Vector3 into TransformPointToLatLonAlt, but it’s super inaccurate at best.

**Comment by kircher1** [comment]
The altitude on the MapPin is relative to the AltitudeReference (Ellipsoid/Terrain/Surface), so as you say, it won't change over time (unless you're changing it through code/the inspector).

If you need to reverse back the altitude relative to the ellipsoid, what I would have recommended is using MapRenderer.TransformLocalPointToLatLonAlt + the MapPin GameObject's transform.localPosition. (Using the local space conversion would save a matrix multiply compared to using MapRenderer.TransformWorldPointToLatLonAlt + transform.worldPosition) However, if there's some inaccuracy with those transformation's however, then that sounds like a bug.

> How can I get info about ground level altitude in certain LatLon?
> What about LatLon that are outside MapRenderer radius?

To the original question, while you should be able to reverse back the ellipsoid-relative altitude of a MapPin, this won't work for areas out of the map's view. I think folks may be trying to achieve different things possibly, but I'm not sure what the scenario is here so I'm not sure if I'm answering the question.

**Comment by kircher1** [comment]
0.9.0 fixes a few issues that were affecting the accuracy of the transformation extension methods. TransformWorldToLatLonAlt was one affected method that should work correctly now.

**Comment by Pysiokot** [comment]
> but I'm not sure what the scenario is here so apologies if I'm not answering the question.

No problem, I was just wondering what when I want to (for example) simulate Pins positions outside the map. I can get world position of certain LatLonToWorldPoint, but I don't have any information about pins altitude outside the map. This is a problem, when I zoom in / out the map and pins scale changes.

**Comment by kircher1** [comment]
The other issue with trying to render pins outside the map bounds is that they are going to be continually disabled when they go out of view. I supposed you could have a script that always to reenable the GameObject, and then if you had cached the altitude (derived from the pin's position using LatLonAltToWorld), you could rederive the position itself using TransformLatLonAltToWorld. 

That being said, I'm still not sure the benefit of a scenario where pins should stay visible outside the bounds of the map itself. However, if we can show this being useful, then that could become an option in how MapPins are managed, i.e. provide a bool to turn off the behavior which disables and stops updating MapPins which are out of view. FWIW, all the [MapPin-related code](https://github.com/microsoft/MapsSDK-Unity/tree/master/SupportingScripts/Runtime/Scripts/MapRenderer/MapPin) as of 0.9 lives in the OSS Supporting Scripts.

**Comment by SiriusA7** [comment]
@kircher1  Is there a way to get notified when all the ElevationTiles are loaded in? The MapPins transform won’t be updated until there’s an elevation tile under it, or at least so it seems.

**Comment by kircher1** [comment]
There's currently no notification for that, or more generally, when the map data for the current view has resolved (#31). That being said, the MapPin GameObject's position (and more specifically it's y coordinate in local space, i.e. the altitude axis) should be updated within a handful of frames of whenever the underlying elevation data has changed.

**Comment by SiriusA7** [comment]
How dramatic is the elevation data accuracy difference between fully zoomed out and fully zoomed in?

To the point of the original question though, a call or something similar to google maps elevation api would be useful for the purpose of pre-processing a list of LatLons to get their associated Altitude. And then using that list of LatLonAlts for a something like an elevation accurate lineRenderer that doesn’t require each point in the line to be a gameObject. The current workaround feels... extra...

Perhaps a LatLonAlt that takes an AltitudeReference would help as well.

**Comment by kircher1** [comment]
The elevation accuracy will be vastly different at lower zoom levels than higher ones but perceptually, when the map is zoomed out so far, even vast differences in altitude aren't visibly noticeable.

So line rendering is an interesting example, and actually in 0.9.0, we opened the door to have a less round-about way of doing this via an IPinnable interface and [`MapRendererBase.TrackAndPositionPinnables`](https://github.com/microsoft/MapsSDK-Unity/wiki/Microsoft.Maps.Unity#maprendererbase)/`MapRendererBase.UntrackPinnable`. If one was to implement a line renderer on top of this, you would need to store of list of corresponding IPinnables for each vertex in the line and then call `TrackAndUpdatePinnablePositions` each frame to get the updated position of the line in local space. Then these pinnable positions would need to be synced back to a line renderable's vertices. This is a little less round-about than using the MapPin system, but it's basically a layer deeper, i.e. this is the same APIs the MapPins use to position themselves. 

Once the map is at a higher level of detail, zooming in and out could still produce differences in the elevation across LODs, but it shouldn't be huge. There are scenarios where it could be though, e.g. someone is overriding the elevation layer with their own data that isn't shown until LOD N, and then at that point there is a vastly different elevation value from the default layer... So while you can cache an altitude to begin with, and never worry about resampling it again, the point of `TrackAndUpdatePinnables` is to handle this for you and always provide a position that best reflects the the current surface being rendered on the map. Moreover, it's meant to be performant in that the elevation sampling is getting queued into an async workload so that it's not directly impacting framerate. Plus it caches previous results so that it doesn't have to continually recompute these elevation offsets, only when the data changes or the pin location changes... This is all especially important when there are many pinnables that need to be updated in a given frame. This does cause sometimes a delay in the actual altitude offset being positioned correctly, but it's usually only a frame or two. A final note here though is that the elevation sampling only applies to AltiudeReferences of Terrain/Surface. If the pinnable is set to ellipsoid, the map surface isn't a factor.

That's really just a long way of saying, try out these new APIs if you're attempting to build a line renderer ontop of the map! That's something I expect we will be looking into as well, i.e. a built-in solution for rendering geospatial lines but I think the pieces are there now to build a simple implementation.

**Comment by kircher1** [comment]
0.9.1 adds the transformation methods of `TransformMercatorWithAltitudeToLocalPoint` and `TransformLatLonAltToLocalPoint`. Both transformations were possible before with some extra conversions before calling the existing methods, but these are ultimately the methods you would want to use when doing some sort of MapPin-like implementation. Positioning the content in the map's local space allows the content to be a child of the MapRenderer's GameObject rather than constantly being sychronized with it's local-to-world transformation.
