### ISSUE TITLE
development for Hololens

### ISSUE THREAD

**Issue by AnushaFatima** [Microsoft/MapsSDK-Unity#6]
I would like to know how unity project with map can be deployed on hololens using visual studio. How to view the project in hololens through unity?Is it compulaory to install windows insider ?

**Comment by kircher1** [comment]
If you are using the sample project, it does require installing the insider SDK as explained in the docs. This is due to the inclusion of MRTK in the sample project. This new version of MRTK integrates with the HoloLens 2 related APIs from the newest version of Windows and thus requires the insider SDK to build.

If you are not using the sample project, i.e. you have just imported the Core package from the Releases page, then you don't need to worry about installing the preview version of the SDK. Just make sure your project is setup to target UWP and "Virtual Reality Supported" is enabled in the player settings.
