### ISSUE TITLE
0.9.0 Update removes MapNavigation

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#64]
After the update, custom scripts that relied on MapNavigation are giving the following error:

"_The type or namespace name 'MapNavigation' could not be found (are you missing a using directive or an assembly reference_?"

We have scripts that use public MapNavigation methods such as Pan and Zoom. What is the proper way to update these?

**Comment by kircher1** [comment]
Apologies-- this was a stale script that hadn't been getting updates. Since you're still getting use out of it, I created a PR (https://github.com/microsoft/MapsSDK-Unity/pull/65) to bring it back and address the breaking changes from 0.9.0.

This will be merged into the SDK in the next release. For now though, you can copy the cs and cs.meta file down to your project.

**Comment by kircher1** [comment]
This is fixed in 0.9.1, but note the script has been renamed to `MapInteractionController`-- we wanted to avoid future conflicts with any sort of routing/navigation functionality.

The component GUID and APIs are the same though, so the only additional work will be to find and replace instances in the code using `MapNavigation` with `MapInteractionController`.
