### ISSUE TITLE
While zooming or panning the map, Map Label Text appear too large for a frame on 0.9

### ISSUE THREAD

**Issue by HKBSC** [microsoft/MapsSDK-Unity#68]
**Describe the bug**
Map Label Text objects appear too large and about 2 meters above the map surface, the first time they are loaded.

**To Reproduce**
1- Open City Tour example and disable Seattle Tour script so it doesn't animate.
2- Hit play
3- Move camera high enough to approx 5 meter or more
4- Manually zoom out or pan map.
5- Observe Text Labels popping up above the map at the first frame they are brought into the map boundary for the first time.

Same thing happens in any other scene with map labels

**Expected behavior**
Text should appear on the map at correct scale as prior to 0.9 update.

**Screenshots**
Single frame from video capture:
![MapsLabelBugScreenshot](https://user-images.githubusercontent.com/63201460/84829235-6a179480-aff5-11ea-8c55-229c63d71323.JPG)

**Environment (please complete the following information):**
 - Unity version: [e.g. 2019.4.0f1]
 - Maps SDK Package Manager Package version: 0.9

**Comment by kircher1** [comment]
Thanks for the bug report. I haven't been able to repro it actually, but it might because the order of scripts being executed. I see how this could happen though and a fix for this will be included in the next version.

If needed, a workaround could be to set the label prefab's scaling to 0 so for that first frame where it's incorrect, it won't be visible.

**Comment by kircher1** [comment]
Fix is in 0.9.1.
