### ISSUE TITLE
HLod support and Map areas in the range of km2

### ISSUE THREAD

**Issue by SimonP01** [microsoft/MapsSDK-Unity#69]
Hello,
First of all: Great work! Your SDK works and looks very nicely.
I would like to have two questions though: 

1. I did play around with it a little and it seems to me there is no distance based lodding right now, correct? 
2. The maximum extends of the map are clipped to a fairly small number. I understand this is due to performance constraints. However, is there a way to lift those constraints? 

Thank you very much for your insights,
Cheers,
Simon

**Comment by kircher1** [comment]
Hello! Correct, there is no way to lift the restrictions on the map size. You can still scale the map up with the Unity transform, increase the map layout size to it's max (3x3 I believe), and increase the Detail Offset to 1.0. This is the limit of what is possible currently.

The constraint on the map size is due to performance. Making it larger would render too much data because there is no dynamic LOD'ing happening (currently). It seems like what you are looking for is what we are referring to as 'immersive mode'. Duping to that feature request. https://github.com/microsoft/MapsSDK-Unity/issues/2
