### ISSUE TITLE
Usage of MapRenderer.SetMapScene() inside Editor

### ISSUE THREAD

**Issue by Neutrinora** [microsoft/MapsSDK-Unity#71]
Following states belongs to process of adding a MapRenderer to the scene inside **Editor** (not play mode)

> State 1 - MapRenderer Created
> State 2 - Starts Downloading Tiles in View
> **State 3 -** 
> State 4 - MapRenderer GameObject Deselected
> **State 5 -** 
> State 6 - Completes Downloading Tiles in View
> **State 7 -** 
> State 8 - MapRenderer GameObject Selected
> **State 9 -**

I want to use following method inside Editor;
MapRenderer.SetMapScene(targetMapScene, MapSceneAnimationKind.None);

Using this method on:

> **State 3, State 5, State 9** > Works as expected
> **State 7** > Doesn't work until i select MapRenderer GameObject

Using on **State 5** works as expected even gameobject is not selected, that's why i'm hopeful there would be a way to trigger that behaviour again?

**Comment by Neutrinora** [comment]
Disabling and enabling MapRenderer script solved my problem.
MapRenderer.enabled = false;
MapRenderer.enabled = true;

Not closing the issue for now to hear correct solution if it exist.

**Comment by kircher1** [comment]
I haven't been able to reproduce this issue actually, so my setup may be incorrect.

One thought though is that the script that calls `MapRenderer.SetMapScene` should be marked as [ExecuteInEditMode].

**Comment by Neutrinora** [comment]
[ExecuteInEditMode] and [ExecuteAlways] was not effective. I've tried both before. Even i tried MapRenderer's [ExecuteInEditMode] to [ExecuteAlways]

I have a CustomEditor class which shows GUI objects within OnSceneGUI() method.
Also SetMapScene() always gets called. Latitude & Longitude on MapRenderer changes as expected. Instead it doesn't start downloading tiles while MapRenderer GameObject is not selected.

Unity Version: 2019.4.0f1 LTS

**Comment by kircher1** [comment]
Ok, I have a better idea now. I think the issue is that the MapRenderer only causes the player to update in the editor when it's inspector is active (i.e., visible). This behavior is due to how MapRendererEditor is implemented. See how `EditorApplication.QueuePlayerLoopUpdate();` is used in that class.

To make this scenario work, where SetScene is being called from a different inspector, you'll need to queue player updates for sometime after the scene has been set. Unfortunately we don't currently have a way to know when the map has finished loading (#31 for future reference), so the best you can do is to continually queue player update loops while your inspector has not yet been destroyed, or use some fixed amount of time (like 5 seconds) to queue updates after the scene has been set.

**Comment by Neutrinora** [comment]
Calling "EditorApplication.QueuePlayerLoopUpdate();" worked as expected. Great solution.
Thank you very much for your time.
