### ISSUE TITLE
Coordinate transformation

### ISSUE THREAD

**Issue by itorresdev** [microsoft/MapsSDK-Unity#74]
I have an entity server connected to this viewer.
The positions are sent in WGS84 (lat long alt), like (42.34545633 30.3435544 1235.56). Alitude in meters.

I need to transform these coordinates to world, so that the entities and the terrain correlate.
I have seen an animation of a hot air balloon on a ground, but I can't find the example. It could be of help.

How can I do this transformation in an optimal way to handle many entities?

**Comment by kircher1** [comment]
Check out the docs around [`MapPinLayer`](https://github.com/microsoft/MapsSDK-Unity/wiki/Attaching-GameObjects-to-the-map) here and see the [SampleProject's MapPinExample scene](https://github.com/microsoft/MapsSDK-Unity/wiki/Sample-project) which loads some 5k points from a csv file, transforms them to Unity GameObjects, and attaches them to the map via the `MapPinLayer` system.

If your data already has altitudes baked in, use `Ellipsoid` for the MapPin's AltitudeReference rather than Surface or Terrain, as the latter options would make the altitude relative to the map's terrain surface which seems like something you would not want for this case since you already have an altitude value. Plus, it's more perf intensive to have to account for surface offset when positioning MapPins, so using Ellipsoid is better in that sense too.
