### ISSUE TITLE
Identifying common building parts such as windows from a RaycastHit

### ISSUE THREAD

**Issue by yosun** [microsoft/MapsSDK-Unity#87]
Just wondering if it is possible to identify building parts such as windows via this SDK... 

(If not, please add this as a feature!)

**Comment by kircher1** [comment]
Similar answer to the other issue, but this is not possible and more dependent upon the data the SDK consumes which currently does not have this sort of information (e.g. window locations).

**Comment by yosun** [comment]
I'm thinking of writing kind of a manual hack for this, at least for known buildings. Can you let me know if this is the best  approach? 

- Export the highest res model of a building available (is there a built in or official way to do this?) 
- Use Revit/3DS Max to add BIM structure data like windows and export as a well-named fbx "invisible collider with children such as window ID etc" to Unity
- Import this "collider" fbx and overlay it as a collider on the building, and scale accordingly based on zoom level

**Comment by kircher1** [comment]
Yes, I think it is a good idea. A shadow mesh could be annotated or subdivided in such a way so that a hit test can be used to determine what part of a building you are hitting.

Generating that sort of data could be more of the issue though as it's not available through the SDK and there is no way to export the meshes. Exporting the map data is also not allowed via TOU, so that likely won't be a feature added to the SDK either.

Of course if you have specific buildings in mind, maybe there is some existing BIM data for it that could use as a good starting point? Assuming the BIM data is accurate, it should match the building on the map closely. Just be sure to use the "realistic scaling" option on the MapPin.
