### ISSUE TITLE
Map Pin Altitude

### ISSUE THREAD

**Issue by huzeyfecoskun** [microsoft/MapsSDK-Unity#93]
I am writing custom shape drawing module. My question is when i zoom in to map and draw shape then pin it to the map altitude of gameobject is set to "X" then i zoom out the map then draw another shape on same LatLon then pin object. This time the altitude is changing like "Y" so X is not equal to Y but i pin objects to the same coordinate.

What i want is i want to make flat map. No altitude just pin the object on X, Z coordinate and want to keep Y coordinate as i set. How can i do that ?

Thanks in advance.

**Comment by kircher1** [comment]
If the altitude you're pinning the object to is determined by a raycast, that altitude value is going to be based on the current level of detail the map is being rendered at. When zooming out or in, the map data would change and so would the altitude of that specific LatLon.

If you don't need the 3D terrain, you could indeed render a flat map. See the [Map Terrain Type](https://github.com/microsoft/MapsSDK-Unity/wiki/Configuring-the-MapRenderer#map-terrain-type) for more info. This can be changed through the editor UI too.

If you'd like to continue using the 3D terrain, instead of pinning the object to the exact altitude value, use altiude = 0 and an AltitudeReferenceType of Surface for the MapPin. Then the shape's altitude would be updated to follow the terrain as it changes.
